name: commentcheck
on:
  issue_comment:
    types: [created]

jobs:
 job01:
    name: My comment checker
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/commenttest') && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER')
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get github.repository
        run: |
          echo ${{ github.repository }}
